# Generated by Django 5.1.4 on 2025-07-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recipe_name_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='users/default_avatar.png',
                                    null=True, upload_to='users/', verbose_name='Аватарка'),
        ),
    ]
